name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x' # Specify the .NET version you're using

      - name: Extract version
        id: get_version
        run: |
          version=$(grep -oP '(?<=<Version>)[^<]+' OpenConstructionSet/OpenConstructionSet.csproj)
          echo "##[set-output name=version;]$version"

      - name: Build and Test
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output nupkgs

      - name: Publish
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Tag commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Clean up
        run: rm
